src/util/MongoBinaryDownload.js
tried these locally and seem to work
=> win32 binary path fix

src/MongoMemoryServer.js, src/util/MongoInstance.js, src/util/__tests__/MongoInstance-test.js
=> wait for mongod process to exit before removing its files

src/util/MongoBinaryDownloadUrl.js, src/util/__tests__/MongoBinaryDownloadUrl-test.js
=> GH-43 download legacy build for unknown os

src/MongoMemoryReplSet.js
It was apparently way too late, 2 AM, when I submitted my last PR. I cleaned this up to emit state changes as explicit events. This makes it easier to clean up event listeners, and makes it so the `waitUntilRunning` method doesn't add and never remove an event listener. Sorry about the original version being less ideal.
=> Emit ‘init’, ‘running’, and ‘stopped’ to allow for easier cleanup of listeners.

.gitignore, src/util/MongoBinaryDownloadUrl.js, src/util/__tests__/MongoBinaryDownloadUrl-test.js
=> List latest Ubuntu version

.travis.yml, README.md, package.json, src/util/MongoBinary.js, yarn.lock
Fixes https://github.com/nodkz/mongodb-memory-server/issues/95
=> switch to node_modules/.cache directory instead of $HOME for binaries DL

src/MongoMemoryServer.d.ts, src/MongoMemoryServer.js
Regarding this issue : https://github.com/nodkz/mongodb-memory-server/issues/108
=> Remove unused variable isRunning

src/util/MongoBinary.js
This fixes an issue we are having using this with windows
also fixes for the user in issue 139
=> check for spaces and wrap in quotes

src/MongoMemoryReplSet.js
=> Include storageEngine option in replica sets

README.md
=> Fix Typescript Reference

README.md, package.json, packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/resolve-config.ts, packages/mongodb-memory-server-global-3.4/postinstall.js, packages/mongodb-memory-server-global-3.6/postinstall.js, packages/mongodb-memory-server-global-4.0/postinstall.js, packages/mongodb-memory-server-global/postinstall.js, packages/mongodb-memory-server/postinstall.js
Continuation of #167 
I've tested it best to my ability, but it was a bit more complicated than previously due to multiple modules. Please check before merging.
=> feat(install): configure installation from package.json

README.md
This is a fix for the examples as specified here #181
=> Update example imports

package.json, packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts
ReplSetOpts.dbName is optional (https://github.com/nodkz/mongodb-memory-server/blob/master/packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts#L70)
=> ReplSetOpts.dbName is optional

README.md
Thanks for this package.
I wanted to clarify some auto-download behavior which wasn't clear in the README. For instance, I assumed that the core package never tries to auto-download the binary. But that is only true upon installation.
Hopefully this makes things clearer for other users.
=> Clarify readme wording and auto-download behavior

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts
=> fix: add debian buster downloads

README.md
I think it will be very useful for further googlers
=> Improve ReplicaSet example with mongoose code

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts
Reverts nodkz/mongodb-memory-server#229
=> Revert "fix: add debian buster downloads"

README.md
Hello,
This is a tiny follow-up to #66.
Have a nice day and thanks for this awesome library.
=> Add a note for users behind a proxy

.github/CODEOWNERS, .vscode/settings.json, README.md, packages/mongodb-memory-server-core/.gitignore, packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer-test.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/getos/index.ts, packages/mongodb-memory-server-global/README.md
- Improving examples
- Adding TSDoc
- making code more readable
- adds a static function `create` so that an instance can be created, autoStarted and awaited
- change internal functions (inferred by starting with `_`) to identifier `private`
---
PS: do not merge yet, until all the comments below are resolved, thanks
---
fixes #211
=> Improve Example code & adding TSDoc

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload-test.ts, packages/mongodb-memory-server-core/src/util/resolve-config.ts, packages/mongodb-memory-server/postinstall.js
Adding Issue Templates:
- Bug
- Questions
Adding a Pull Request Template
Adding a note on what is needed to detect the Linux Distro
fixes #248 
fixes #255
=> Adding Templates & note about linux distros

packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer-test.ts, packages/mongodb-memory-server-core/src/types.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts, packages/mongodb-memory-server-core/src/util/db_util.ts, packages/mongodb-memory-server-core/src/util/deprecate.ts, packages/mongodb-memory-server-core/src/util/resolve-config.ts
- add TSDoc to MongoInstance
- add `@deprecated` to `getConnectionString` (TSDoc deprecated)
- rename some variables to make more sense
- fixed some types
(This is a draft, because of some `TODO: ask` notes)
=> Add TSDoc to MongoInstance

packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts
- Change watch script to use "--watchAll"
- Remove "this.admin" because it is not used outside of one function
- Add an counter to how many instances are spawned for better logging
=> Small Changes

packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
- Handle Status Codes other than 200 (it shouldnt run infinitely anymore if the download fails)
- Add some TSDoc
this should hopefully fix #226 (at least that what the issue evolved into)
- fixes #226
=> Handle Status Codes other than 200

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/replset-single-restart-test.ts
=> fix: catch reinit of replicaset

packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
This is a quick one, I've just upgraded my servers to coreos 8 and this is causing issues.
=> Add support for rhel & coreos 8

packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts
- fix(MongoBinaryDownload): add debug log for url
- fix(MongoBinaryDownload): put "stdout.write" in an "isTTY" and otherwise use "console.log"
- rename script `cleanup` to `clean`
- suggested in #226
=> add debug log for url

packages/mongodb-memory-server-core/package.json, yarn.lock
- closes nodkz/mongodb-memory-server#298
=> fix: remove stub package "@types/get-port"

.github/workflows/stale.yml
- fix workflow "stale", i added key `only-labels`, which i read wrong, it only gets issues **which match all listed labels**
=> chore: fix workflow "stale"

.eslintrc.js, packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/__tests__/multipleDB-test.ts, packages/mongodb-memory-server-core/src/__tests__/singleDB-test.ts, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts, packages/mongodb-memory-server-core/src/util/getos/index.ts
- add eslint rule `curly`, set to `error, all`
- apply eslint rule
- closes #275
=> style: add eslint rule "curly" set to "all"

README.md
- change CircleCI build badge to Github Actions Badge
- add codecov badge
=> style(README): change badges

packages/mongodb-memory-server-core/jest.config.js, packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer.test.ts, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl.test.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoInstance.test.ts, packages/mongodb-memory-server-core/src/util/__tests__/utils.test.ts
- getSystemPath: return "undefined" instead of empty string
- feat(MongoInstance): remove function "getPid" (because it was mostly unused)
- fix(MongoMemoryReplSet): remove unnecessary default to empty array
- style(MongoMemoryReplSet): remove commented-out case
- style(MongoMemoryReplSet): remove TODO
- add some tests
- closes #392 (because an commit in this pr removes the todo for this issue)
=> some cleanup & more tests

packages/mongodb-memory-server-global-3.6/index.js, packages/mongodb-memory-server-global-3.6/postinstall.js, packages/mongodb-memory-server-global-4.2/index.js, packages/mongodb-memory-server-global-4.2/postinstall.js, packages/mongodb-memory-server-global-4.4/index.js, packages/mongodb-memory-server-global-4.4/postinstall.js, packages/mongodb-memory-server-global/postinstall.js, packages/mongodb-memory-server/postinstall.js
Resolves https://github.com/nodkz/mongodb-memory-server/issues/438
=> Postinstall module paths

packages/mongodb-memory-server-global-3.6/package.json, packages/mongodb-memory-server-global-4.2/package.json, packages/mongodb-memory-server-global-4.4/package.json, packages/mongodb-memory-server-global/package.json, packages/mongodb-memory-server/package.json
Resolves https://github.com/nodkz/mongodb-memory-server/issues/445
=> Add tslib dependency

packages/mongodb-memory-server-core/jest.config.js, packages/mongodb-memory-server-core/src/__tests__/testUtils/globalSetup.ts
test globalSetup before merging into main branches
=> test: add "globalSetup" to ensure versions are downloaded before tests

packages/mongodb-memory-server-core/src/util/resolveConfig.ts
Resolves https://github.com/nodkz/mongodb-memory-server/issues/440
=> fix(resolveConfig): resolve download dir and system binary relative to found package.json

README.md, docs/guides/integration-examples.md, packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer.test.ts, packages/mongodb-memory-server-core/src/__tests__/__snapshots__/MongoMemoryReplSet.test.ts.snap, packages/mongodb-memory-server-core/src/__tests__/__snapshots__/MongoMemoryServer.test.ts.snap, packages/mongodb-memory-server-core/src/util/errors.ts
- fixes #458
- fixes #497 
- fixes #501 
- fixes #499 
---
also fixed an spelling mistake pointed out by #502
=> Fixup docs and errors

packages/mongodb-memory-server-core/src/util/MongoInstance.ts
Nothing much to say here, it just caught my eye. Thank for writing such a great library...
=> style(MongoInstance.ts): fix typo

docs/guides/migrate7.md
=> Fix migrate7 code example for getUri() method

packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload.test.ts, packages/mongodb-memory-server-core/src/util/__tests__/dryBinary.test.ts, packages/mongodb-memory-server-core/src/util/lockfile.ts, packages/mongodb-memory-server-core/src/util/utils.ts, yarn.lock
Remove Dependency `mkdirp` in favor of native `fs.mkdir` with options `recusive: true`
=> Remove Dependeny `mkdirp`

docs/api/config-options.md, packages/mongodb-memory-server-core/src/util/DryMongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload.test.ts, packages/mongodb-memory-server-core/src/util/__tests__/dryBinary.test.ts, packages/mongodb-memory-server-core/src/util/getos/index.ts, packages/mongodb-memory-server-core/src/util/resolveConfig.ts
=> feat: add environment variable to use archive name for binary name

docs/guides/integration-examples/test-runners.md
=> Update test-runners.md to fix grammar errors
