typegoose/mongodb-memory-server

README.md
Sometimes you use the name `mongoServer` and other `mongod` to represent an instance of MongodbMemoryServer.
How could we improve the consistency of documentation?
> PS.: mongod remembers me mongo-daemon :smile:
=> fix(typo): from "mongoServer" to "mongod"

README.md, src/MongoMemoryServer.js, src/util/MongoBinary.js, src/util/MongoBinaryDownload.js, src/util/MongoBinaryDownloadUrl.js, src/util/__tests__/MongoBinaryDownloadUrl-test.js
Referenced to this [issue](https://github.com/nodkz/mongodb-memory-server/issues/55)
Now binaries for OSX older than 3.0 version is immediately installed with the SSL. Before and including 3.0 - without.
Since the SSL is not used anywhere else, it is completely removed from the code
=> fix(MongoBinaryDownloadUrl): removed `ssl` from options

src/MongoMemoryServer.js
According to `get-port` [docs](https://www.npmjs.com/package/get-port) preferred  port should be passed in as object.
Resolves #71
=> Pass port as object to get-port

src/index.d.ts, src/index.js
Apparently I forgot to copy the export details from the flow version to the TypeScript definitions for the package's index file. Whoops!
=> chore(exports): Add MongoMemoryReplSet to package exports.

src/util/MongoInstance.js, src/util/__tests__/MongoInstance-test.js
As referenced in [issue 111](https://github.com/nodkz/mongodb-memory-server/issues/111) PR 79 doesn't add auth to the command line arguments (prepareCommandArgs()) even when instance.auth is set to true.
This PR allows auth to be passed as a command line argument.
=> allow authorizations

postinstall.js
We were trying to figure out why this doesn't work (before 2.7.3 in the postinstall) and found this code confusing so I figured I'd contribute back and clean it up (thanks for the library!)
=> clean up skipDownload code

README.md, postinstall.js, src/util/MongoBinaryDownload.js, src/util/__tests__/MongoBinaryDownload-test.js
There are several changes in this pull request:
- add error handling in postinstall.js script for verbose error during downloading and installation
- add MONGOMS_SKIP_MD5_CHECK environment variable for skipping MD5 check with the reference result
FYI: md5 sum has been updated in the MongoDB mirror, so I removed my workaround in MongoBinary-test.js. Even this pull request currently isn't required, I think it's good to have such option for the future.
=> add MONGOMS_SKIP_MD5_CHECK environment option

src/util/MongoBinary.js, src/util/__tests__/MongoBinary-test.js
Trying to use the MongoBinary on my alpine container and ran into an issue where it can't find the binary file i pass in even though the binary exists.  Trace down the problem and is seem to be related to fs.access() throwing the error where callback is not defined.  fs.access is not a promise so we need to promisify for the code to work.
=> fix: promisfy fs.access in getSystemPath

src/util/MongoInstance.js, src/util/__tests__/MongoInstance-test.js
When a `MongoInstance` is killed, the `killerProcess` should also be killed. Else `jest` may fail in other projects, since there remains an `open handle` for the `killerProcess` until the interval (2s)  is called, see  [Mongo Killer Interval](https://github.com/nodkz/mongodb-memory-server/blob/b59ed826dd4f3cd31ad6f05c890f70eaad034abd/src/util/mongo_killer.js#L32).
=> fix(MongoInstance): kill the `killlerProcess` on instance kill

src/util/MongoBinary.d.ts, src/util/MongoBinaryDownload.js
Also,
- Fix TS typings to accept documented `binary.checkMD5` flag.
=> Fix #136 - Fix MD5 check failing due to validating minimum size for MD5 file itself

src/MongoMemoryServer.js
I was running into an issue where I was trying to set the `ip` option but the mongod command that was spawned still had '127.0.0.1' in it. I believe the option is never actually being passed in.
=> Pass instance ip option to MongoInstance.run

README.md, src/MongoMemoryReplSet.ts
Here's a Pull Request to allow additional settings when initializing a replica set:
```js
const replSet = new MongoMemoryReplSet({
replSet: {
configSettings: {
electionTimeoutMillis: 100,
},
},
})
await replSet.waitUntilRunning()
```
=> Support for replSetInitiate settings

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
It used to download the release for ubuntu 14.04 for any elementaryOS.
But different elementaryOS versions use different ubuntu base version.
So there is a need to check ubuntu versuin first and then use it to generate archive name.
=> fix(downloadUrl): elementaryOS support fixed for versions up to 0.3

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
An addition to #169
Forgot to put extra `.trim()` to take out the `\n` in the end of stdout from the command. Now is fixed.
=> Elementary os fixed

packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/util/MongoInstance.ts
Fixes #180 
Ok, let's try this one more time with feeling. I used `npm pack` (thanks for the tip on the last PR) this time around to test, and I can confirm that this solves the problem for me on Windows.
As a side note, I am still seeing an `Error: EBUSY: resource busy or locked` when I try to close the database connection, but that was there before and should probably be a separate issue.
=> Use cross-spawn to help with Windows issues (take 2)

packages/mongodb-memory-server-core/src/util/__tests__/resolve-config-test.ts, packages/mongodb-memory-server-core/src/util/resolve-config.ts
Fix for #187.
This also introduces reInitialisePackageJson() for test scripts. (There might be a cleaner way of doing this with `jest.resetModules()`, but I couldn't figure out how to make it work with TypeScript/ES6 imports.)
It's worth pointing out that if you have a monorepo such as the structure below and you run jest from the project directory then `subproject/test.js` will pick up the config from `project/package.json` whereas if you run jest from inside the subproject directory (or use a tool like lerna which does the same thing) then it will pick up config from `subproject/package.json`. This seems fairly logical to me, and probably as good as we can get, but perhaps others might disagree.
```
project
|-- subproject
|   |-- package.json
|   |-- test.js
|   +-- ...
|-- package.json …
```
=> fix: resolve to config from closest package.json

packages/mongodb-memory-server-core/src/util/MongoBinary.ts
Fixes #168. The RegExp check is failing with Windows path separators because `\` is treated as a RegExp escape sequence.
I'm not able to get the project to build/run, but I'm pretty sure the logic is equivalent.
=> Simplify postinstall path check

packages/mongodb-memory-server-core/src/util/__tests__/resolve-config-test.ts, packages/mongodb-memory-server-core/src/util/resolve-config.ts, packages/mongodb-memory-server/postinstall.js
Fix for issue spotted by @kjarmicki with https://github.com/nodkz/mongodb-memory-server/pull/191
This makes reInitializePackageJson() in resolve-config.ts into a semi-public interface, used by postinstall.js, taking an optional directory argument to search from.
I'm not 100% happy with this solution. I feel like it's a poor interface to have singleton config that can be poked at in this way. It opens up the possibility of action-at-a-distance. Perhaps resolve-config itself should know about INIT_CWD. That would at least make its behaviour more predictable, at the cost of making it somewhat dependent on the details of npm. As always, I'm open to better suggestions.
=> fix: re-initialise configuration using INIT_CWD in postinstall.js

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/__tests__/replset-test.ts, packages/mongodb-memory-server-core/src/types.ts
My attempt to has deterministic implementation for waitUntilRunning for replicaSet, which is discussed in #74 .
Was testing if there is way to tell if its ready from `replSetGetStatus`, but my testing shows it rather shows the intention (whats going to be master) rather than actual real time status. With debug info from mongod - you can see that mongod instance is transitioning from secondary state to primary state (after voting) which takes about 2s. Also my testing shows that you get connect error until this transition is finished. And only reliable approach I found was using `serverStatus` which indicates in realtime whether its master or secondary.
Obviously `serverStatus` gives me status for the instance I am connect to, which is first server. Therefore this strategy would fail if …
=> Addressing #74 - Wait until primary is transitioned from secondary for replicaSet

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts
This allows overriding just a single replSet property in our test files. It shouldn't cause any issues as all changed properties already have default values.
It solves [this](https://github.com/nodkz/mongodb-memory-server/issues/189) issue.
=> Make properties of replSet optional

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts
I like this version more than #203 , because should handle correctly if any of the mongod becomes the master, not just the first one, which might be causing these occasional infinite waits on CI.
@nodkz What do you think? :-)
There is not much more I can contribute promptly. Leaving for 2 weeks holiday tomorrow and have some important things to finish off today. So hopefully this will resolve previous issues.
=> Follow-up for 203 detect primary from stdout instead of admin call

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts
Fixes #216 
Here's what I see on https://www.mongodb.com/download-center/community
New 4.2.0 URL format is:
https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.2.0.tgz
Previous 4.0.12 format was:
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.0.12.tgz
The change is from `osx-ssl` to `macos`. I've attempted to change this in the code, but don't have lerna installed so haven't actually run the tests.
=> URL for macos change for 4.2.0

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts
Hi!
My tests were hanging even after stopping the replica set, so I investigated why - turns out there is an open timer that is not cleared
=> clearTimeout when waiting for primary in replete

package.json, packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/__tests__/multipleDB-test.ts, packages/mongodb-memory-server-core/src/__tests__/replset-test.ts, packages/mongodb-memory-server-core/src/__tests__/singleDB-test.ts, yarn.lock
Currently, when running my tests I receive a lot of deprecation notices (see attached img), looks like MongoDB is deprecating his current topology system so they need the `useUnifiedTopology` flag set, i'm sending this PR to correct that, I also upgraded `@types/mongodb` since it was needed for this support.
PS: this project is great, keep it up y'all :)
=> Using "useUnifiedTopology" to avoid deprecation msg

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
Debian 10 uses libcurl v4, thus needs a different mongodb build
=> Compatibility with debian 10

package.json, packages/mongodb-memory-server-core/package.json
Not including it in devDeps means that `strict: true` TSC projects
using mongoms currently fail to compile with:
```
node_modules/mongodb-memory-server-core/lib/MongoMemoryServer.d.ts:3:22 - error TS7016:
Could not find a declaration file for module 'tmp'.
'node_modules/mongodb-memory-server-core/node_modules/tmp/lib/tmp.js' implicitly has an 'any' type.
Try `npm install @types/tmp` if it exists or add a new declaration (.d.ts) file containing `declare module 'tmp';`
3 import * as tmp from 'tmp';
~~~~~
```
=> Add @types/tmp to dependencies

README.md, packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer-test.ts, packages/mongodb-memory-server-core/src/__tests__/singleDB-test.ts, packages/mongodb-memory-server-core/src/index.ts, packages/mongodb-memory-server-core/src/types.ts, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts, packages/mongodb-memory-server-core/src/util/getos/index.ts, packages/mongodb-memory-server-core/src/util/resolve-config.ts, packages/mongodb-memory-server-core/tsconfig.build.json, packages/mongodb-memory-server-core/tsconfig.json, yarn.lock
- Add Dev-dependency "@types/debug" (the normal `debug` package is already an dependency, but never used)
- Change Typescript lib from "es2017" to "esnext" (just to be sure to be able to work with new things, they will get compiled down)
- Added some Logging to "MongoBinaryDownloadUrl"
- Transformed logging to use "debug"
- "resolve-config" now gets loaded in index as an side-effect (to load MONGOMS_DEBUG)
- Added "Enable Debug Mode" section to README
- Reorganized the README's documented options
- Changed `MONGOMS_DEBUG` to enable `debug.('MongoMS:*')`
- `DEBUG=MongoMS:*` will now work as an environment variable too (cant be disabled)
The only file where i didnt remove `this.debug` is `MongoInstance` because it contains the STDOUT of Mong-Instances
- fixes #262 
---
please know that this …
=> Logging rewrite

README.md
I just fixed a typo, the example for mocha was not working
=> docs(Readme): fix a typo

packages/mongodb-memory-server-core/src/util/MongoInstance.ts
insensitive the regexp when a primary is elected because on mongo 4.4 the stdout message has a capital letter
fixes #292
=> insensitive the regexp when a primary is elected

packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload-test.ts
- #162 postinstall fail on certificate issue:
Reads `'strict-ssl'` from npm config so that users can workaround potential certificate chain issues that prevent downloading the mongodb binary.
Retains the [default as true](https://docs.npmjs.com/misc/config#strict-ssl) if the value is not specified or is a value other than `'false'`.
=> Fix #162 - read strict-ssl from npm config

packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload-test.ts
Fix for #308 :
- Read from environment variable `npm_config_strict_ssl` (i.e. all underscores)
- Will honour whatever the npm config value is. npm/yarn will set true properties to the string 'true' and false properties to an empty string. The current npm default is `true` so even without specifying `--strict-ssl` this will be set to 'true' in environment variables.
=> Fix #308 - read strict-ssl from npm config

README.md
The "Available Options" link points to a non-existing (probably outdated) link
=> Update "Available Options" link

README.md, package.json
- There were no clear sections in the readme on installing mongo above the latest version, eg 4.2.8 on Linux Mint.
- There were no table of contents making the docs hard to jump through, doctoc added for automatically building the main readme
=> docs: explaining clearly how to install non latest binary + toc added

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts
This PR fixes download URL generation for MongoDB 4.4 for macOS and Windows platforms.
=> Fix URL generation for MongoDB 4.4

packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinary-test.ts
This PR updates the code to follow the README.
I noticed the checkMD5 option was not available on the `MongoMemoryServer` class constructor, though the README indicated it is an option.
Here's a quick PR passing through the option to do an MD5 check for the downloaded mongo binary.
I also added two quick log statements in the MD5 check function. If that's a problem I can take them out, but they were useful to me and may be useful to someone else running in debug mode.
=> Match README description for checkMD5

packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts
- add tests for "latest" for macos & windows
- fix "Invalid Version: latest" for macos & windows
- replace all occurences with "dedent" with proper strings
- closes nodkz/mongodb-memory-server#345
- closes nodkz/mongodb-memory-server#335
=> fix: fix "Invalid Semver version"

.github/workflows/stale.yml
- add github workflow "stale"
settings:
- runs once every day
- runs only on these tags: `question,can't reproduce,Needs More Information,needs repro script,stale`
- definitely doesnt run on these tags: `help wanted,docs,enhancement,feature,dependencies`
- marks issues as stale if there is no activity in 60 days
- closes issues when the date tagging with `stale` is older than 7 days
- removes stale tag on activity
=> add workflow "stale"

README.md
- fixes mentions of `latest` while actually being `4.0.14`
- fixes #338
=> docs(README): fix mentions of "latest" while being "4.0.14"

packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts
- print the used URL in the Error as well, because issues mostly get reported without debug enabled
=> fix(MongoBinaryDownload): print used URL in 404 Error

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts
- comment out the hack added by 470f09485d5caa9062fc1c24fb5efc0eb3d7d32f
(almost reverts 470f09485d5caa9062fc1c24fb5efc0eb3d7d32f)
- closes #366
=> fix(MongoMemoryReplSet): comment-out older hack

packages/mongodb-memory-server-global-3.4/postinstall.js, packages/mongodb-memory-server-global-3.6/postinstall.js, packages/mongodb-memory-server-global-4.0/postinstall.js, packages/mongodb-memory-server-global-4.2/postinstall.js, packages/mongodb-memory-server-global-4.4/postinstall.js, packages/mongodb-memory-server-global/postinstall.js, packages/mongodb-memory-server/postinstall.js
- skip "mongodb-memory-server"'s postinstall if "SYSTEM_BINARY" is set
- disable eslint-rule "@typescript-eslint/no-var-requires" for all postinstalls (for whole file)
- closes #370
=> fix(postinstall): skip postinstall if "SYSTEM_BINARY" is set

package.json, packages/mongodb-memory-server-core/package.json, yarn.lock
- fix yarn.lock
- resovle yarn warning "mongodb" versions dont match
=> build: fix yarn.lock & resolve yarn warnings

.releaserc.js, README.md, packages/mongodb-memory-server-global-3.4/README.md, packages/mongodb-memory-server-global-3.6/README.md, packages/mongodb-memory-server-global-4.0/README.md
- remove "global-x.x" packages below 4.2 from releases
- README: add deprecation notice
---
This PR removes the packages 3.4, 3.6 and 4.0 from the automated release,
after this pr has been merged the following commands should be run (by @nodkz)
```sh
npm deprecate mongodb-memory-server-global-3.4 "Deprecated, please use an version >= 4.2 (mongodb-memory-server-global-4.2)"
npm deprecate mongodb-memory-server-global-4.0 "Deprecated, please use an version >= 4.2 (mongodb-memory-server-global-4.2)"
```
the commands above will deprecated the entire package (3.4, 3.6, 4.0) with the message provided, this message will show on install and on the npm pages
---
let me know if an message should be updated
PS: if you need an example of a deprecated package, [i once deprecated …
=> build: remove packages below 4.2 from release

README.md
- fix location of the contributing guide in readme
=> docs: fix contributing guide location in readme

packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload-test.ts
- Added check to skip binary tar download, if the required tar is already present in the location
- closes #303
=> feat: skip binary download when binary tar exists

packages/mongodb-memory-server-global-3.4/index.js, packages/mongodb-memory-server-global-3.6/index.js, packages/mongodb-memory-server-global-4.0/index.js, packages/mongodb-memory-server-global-4.2/index.js, packages/mongodb-memory-server-global-4.4/index.js, packages/mongodb-memory-server-global/index.js, packages/mongodb-memory-server/index.js
This line explicitly exports `exports default` - mongoMemoryServer - received from require.
`if (p === "default") exports.default = m[p];`
=> explicitly export default from mms

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl-test.ts
- add "-2008plus-ssl" if below version 4.1.0 and not just when below 4.0.0
- add test for win32 on version 4.0.14
- fixes #399 
(base is master because this is an "hot-fix")
=> fix(MongoBinaryDownloadUrl): fix win32 download generation

packages/mongodb-memory-server-core/tsconfig.json, packages/mongodb-memory-server-global-3.6/package.json, packages/mongodb-memory-server-global-4.2/package.json, packages/mongodb-memory-server-global-4.4/package.json, packages/mongodb-memory-server-global/package.json, packages/mongodb-memory-server/package.json
change compile target to `es6`
plus sides:
- reduces build size from `~360kb` to `~312kb` (core package)
- easier debug on problems (because the compiled code more resembles the source code)
down sides:
- not being able to run this package in an es5 engine anymore (this is so-or-so already thanks to `engines` and depended packages)
---
this is an separate PR from #396 because this might be an "major" change and debatable (at least from what i observed in typegoose)
main things i could observe (even with runtime warnings & documentation):
issues about "invalid syntax" errors (users tried to run typegoose in an non es6 environment (like nodejs before 10.15) (like #379 in this repository)
PS: documentation (like the other PR's for 7.0) will be added later
=> chore: change "target" to "es6"

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
Hey there, I had an issue with getting this up and running on debian/testing. Here's a  debug log snippet
```
MongoMS:MongoBinary MongoBinary options: {"downloadDir":"/home/jnes/TILLY/delta/jest/node_modules/.cache/mongodb-memory-server/mongodb-binaries","platform":"linux","arch":"x64","version":"4.0.14"} +0ms
MongoMS:getos Trying LSB-Release +0ms
MongoMS:MongoBinaryDownloadUrl Using "mongodb-linux-x86_64-debian-4.0.14.tgz" as the Archive String +0ms
MongoMS:MongoBinaryDownloadUrl Using "https://fastdl.mongodb.org" as the mirror +0ms
MongoMS:MongoBinaryDownload Downloading: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-4.0.14.tgz" +0ms
MongoMS:MongoBinaryDownload trying to download https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian-4.0.14.tgz +0ms
Error: Status …
```
=> Add debian "testing" release

packages/mongodb-memory-server-core/src/util/DryMongoBinary.ts, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/__tests__/dryBinary.test.ts
=> feat: change binary from "base/version/mongod" to "base/mongod-arch-dist-version"

packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer.test.ts
When the server fails to start, the state is left is `running`. 
changing the state to `stopped` allows implementing more complex scenarios over the testkit. 
For example, in case the testkit failed to find a proper binary, I can set the `MONGOMS_DOWNLOAD_URL` environment variable and try again.
ATM, doing so throws because `start` [expects](https://github.com/nodkz/mongodb-memory-server/blob/beta/packages/mongodb-memory-server-core/src/MongoMemoryServer.ts#L256) the state to either be `new` or `stopped`
=> fix(MongoMemoryServer): change state to stopped when start fails

packages/mongodb-memory-server-core/src/util/__tests__/utils.test.ts, packages/mongodb-memory-server-core/src/util/utils.ts
Hi! 👋 Thanks heaps for creating and maintaing such a useful library! 🙇
I noticed that when the Node.js process doesn't have permission to access the OS cache directory, an `EACCES` error is thrown and the process crashes. The following error happens to us in our CI environment:
```bash
EACCES: permission denied, stat '/root/.cache/mongodb-binaries/mongod-x64-ubuntu-4.0.25'
```
This pull request updates the handling of `EACCES` errors to match the way `ENOENT` errors are handled: returning `undefined` from `statPath()` without throwing an error. The result is that a MongoDB binary should be able to be installed to a local directory when access to the OS cache directory is restricted. The JSDoc comment was also updated and a test for this specific case was added.
=> fix(errors): EACCES: do not throw on EACCES

docs/guides/integration-examples.md
The existing mocha example uses what looks like syntax from version 6, which does not work in current version. 
- update the `before` hook in the mocha integration example to work in current version.
=> Docs: Fix broken mocha integration example

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryReplSet.test.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts
Ref: https://docs.mongodb.com/manual/reference/replica-configuration/#replica-set-configuration-document-example
Sample code:
```javascript
const replSet = new MongoMemoryReplSet({
instanceOpts: [
{
args: ["--quiet"],
replicaMemberConfig: {
arbiterOnly: true,
},
},
],
});
```
- fixes #209
=> Mongo Replica set - Add replicaMemberConfig to replica instance

README.md
[Noticed that it's now an empty string.](https://github.com/nodkz/mongodb-memory-server/blob/394ca2b35f9ca0636bf3e9c71788a142955ea000/packages/mongodb-memory-server-core/src/util/utils.ts#L16) I was using the `dbName` value in my tests and upgrading to >7.0 broke my suite. This should help others when upgrading past 7.0
=> Fix dbName default doc in README.md

README.md
This is just a very minor change to fix a broken link to a documentation page.
This link does not exist in the doc: https://nodkz.github.io/mongodb-memory-server/docs/guides/integration-examples
So I replaced it with a link to the first page of the integration section (test runners).
=> Updating a broken link

docs/guides/error-warning-details.md, packages/mongodb-memory-server-core/src/__tests__/__snapshots__/MongoMemoryReplSet.test.ts.snap, packages/mongodb-memory-server-core/src/__tests__/__snapshots__/MongoMemoryServer.test.ts.snap, packages/mongodb-memory-server-core/src/util/errors.ts
=> docs: update migration docs urls to include new /migration path (closes #571)

packages/mongodb-memory-server-core/src/MongoMemoryServer.ts, packages/mongodb-memory-server-core/src/__tests__/MongoMemoryServer.test.ts
This closes #573: a folder without any files indicates a new database.
- #573
=> fix(MongoMemoryServer): invert `isNew` for dbPaths

docs/guides/integration-examples/docker.md
This PR fixes a bad typo in documentation.
We write `dockerfile` instead of `dockefile`
=> docs(docker): fix dockefile typo

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts
Add current openSUSE Leap release version (15) to the regular
expression. The change should fix the creation of the DownloadURL for
openSUSE Leap 15.x.
Only tested on openSUSE Leap 15.3.
Signed-off-by: Jürgen Löhel <juergen@loehel.de>
=> fix(MongoBinaryDownloadUrl.ts): Add current openSUSE Leap release version

README.md, docs/guides/known-issues.md, docs/guides/quick-start-guide.md
I encountered this issue while trying to run `mongodb-memory-server` on a Docker image based on `node:16.9.1-slim`.
=> Add info in README for slim Docker node images

docs/api/config-options.md, packages/mongodb-memory-server-core/src/util/MongoBinary.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinary.test.ts
Fix regex that tests the local mongo binary version so that it can
handle versions that include patches and/or other tags.
- fixes #624
=> fix(MongoBinary): Fix mongo binary matching regex

packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts, packages/mongodb-memory-server-core/src/util/MongoInstance.ts
The launchTimeout option if specified in instanceOpts for MongoMemoryReplSet doesn't get passed into the eventual options for each underlying MongoMemoryServer. This change modifies the base opts type to include launchTimeout as a common instance option. 
I have run the automated tests, but I am not sure exactly what else needs testing.
=> fix(MongoMemoryReplSet): pass-through option "launchTimeout" correctly

docs/guides/supported-systems.md, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl.test.ts
Arch Linux is on OpenSSL 3 (instead of 1.1), like Ubuntu 22.04 (not like 20.04), so currently the `mongod` startup fails because of missing `libcrypto.so.1.1` (unless one has the `openssl-1.1` package installed for this or some other reason).
Tested by making this same change locally in the distributed `node_modules/mongodb-memory-server-core`.
=> download correct package for arch

docs/api/config-options.md, packages/mongodb-memory-server-core/package.json, packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts, packages/mongodb-memory-server-core/src/util/resolveConfig.ts, yarn.lock
Add follow-redirects library to handle 302 redirects on fastdl.mongodb.org
- #785
=> feat(MongoBinaryDownload): follow redirects

packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl.test.ts, packages/mongodb-memory-server-core/src/util/__tests__/__snapshots__/MongoBinaryDownloadUrl.test.ts.snap
VERSION_ID was removed. See
https://tracker.debian.org/news/1433360/accepted-base-files-13-source-into-unstable/
and a similar bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008735
=> fix: Fix binary download on debian testing/unstable

packages/mongodb-memory-server-core/src/util/MongoInstance.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoInstance.test.ts
I've a situation where I listen to kill signals and execute `.stop()` when needed. The replica set has already been killed because the `Ctrl + C` signal is propagated to the whole process group, then I waits forever to connect and send a graceful shutdown.
=> fix(kill): should not try to open a connection to a not running ReplSet

.github/workflows/tests.yml, .github/workflows/website.yml, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl.test.ts
The os string in the download url for amazon linux 2023 should be "amazon2023"
- fixes #825
=> Add support for amazon linux 2023

packages/mongodb-memory-server-core/src/util/getport/index.ts
The current implementation of `getPort()` relies on using `Date.now()`to get the first port to try to launch mongo on, even when the `EXP_NET0LISTEN` flag is set. This causes a couple issues:
- If the `Date` module is mocked, it can result in `getFreePort()` returning the same first port every time.
- If multiple mongos are being started at once in parallel, it's possible for the same first port to be picked leading to port conflicts
In order to better randomize the initial port selection so that port conflicts can be avoided, instead of using `Date.now()` for an initial seed, use `crypto.randomInt()` which should provide more randomness and hopefully avoid some of these race conditions.
- #827
=> fix(getport): Randomize first port using crypto

docs/guides/supported-systems.md, packages/mongodb-memory-server-core/src/util/MongoBinaryDownloadUrl.ts, packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownloadUrl.test.ts, packages/mongodb-memory-server-core/src/util/__tests__/__snapshots__/MongoBinaryDownloadUrl.test.ts.snap
Binaries for Debian 12 are available for MongoDB >= 7.0.3.
See https://jira.mongodb.org/browse/SERVER-77231
- #797
=> fix(MongoBinaryDownloadUrl): support Debian 12 (Bookworm)

docs/guides/supported-systems.md
- https://github.com/typegoose/mongodb-memory-server/issues/782
=> docs: add NixOS section to docs/guides/supported-systems.md

docs/guides/integration-examples/test-runners.md
Added [vitest](https://vitest.dev) integration example
Also linked to the https://github.com/danielpza/vitest-mms package which aims to make it easier to setup up mongodb-memory-server with vitest (DISCLAIMER: I'm the author of the package, I can drop it if that's an issue)
=> docs(guides): add vitest integration example
